import streamlit as st
import pandas as pd

# Page configuration
st.set_page_config(
    page_title="Sales Analytics Dashboard",
    page_icon="📊",
    layout="wide"
)

# ==============================
# CUSTOM DASHBOARD STYLING
# ==============================

st.markdown(
    """
    <style>

    /* KPI Cards */
    [data-testid="stMetric"] {
        background-color: #f8f9fa;
        padding: 18px;
        border-radius: 12px;
        border: 1px solid #e5e7eb;
    }

    /* Sidebar */
    [data-testid="stSidebar"] {
        border-right: 1px solid #e5e7eb;
    }

    /* Buttons */
    .stButton > button {
        border-radius: 8px;
        font-weight: 600;
    }

    /* Section spacing */
    .block-container {
        padding-top: 2rem;
        padding-bottom: 3rem;
    }

    </style>
    """,
    unsafe_allow_html=True
)

# Dashboard title
st.title("📊 Sales Intelligence Dashboard")

st.markdown(
    """
    **Explore sales performance, discover trends, and uncover business insights.**
    
    Use the filters in the sidebar to analyze your sales data interactively.
    """
)

st.divider()

# ==============================
# DASHBOARD NAVIGATION
# ==============================

tab1, tab2, tab3, tab4 = st.tabs([
    "📊 Overview",
    "🔎 Sales Explorer",
    "🧠 Ask the Data",
    "📥 Reports & Data Quality"
])

# Load sales data
df = pd.read_csv("data/sales_data.csv")

# Calculate sales
df["Sales"] = df["Quantity"] * df["Price"]

# Convert Order Date to datetime
df["Order Date"] = pd.to_datetime(df["Order Date"])

# ==============================
# SIDEBAR FILTERS
# ==============================

st.sidebar.header("🎛️ Dashboard Filters")

# Default filter values
if "category_filter" not in st.session_state:
    st.session_state["category_filter"] = "All"

if "region_filter" not in st.session_state:
    st.session_state["region_filter"] = "All"

if "start_date_filter" not in st.session_state:
    st.session_state["start_date_filter"] = df["Order Date"].min().date()

if "end_date_filter" not in st.session_state:
    st.session_state["end_date_filter"] = df["Order Date"].max().date()

# Reset filters
if st.sidebar.button("🔄 Reset Filters"):
    st.session_state["category_filter"] = "All"
    st.session_state["region_filter"] = "All"
    st.session_state["start_date_filter"] = df["Order Date"].min().date()
    st.session_state["end_date_filter"] = df["Order Date"].max().date()

    st.rerun()


# Category filter
category_options = ["All"] + sorted(df["Category"].unique())

selected_category = st.sidebar.selectbox(
    "📂 Category",
    category_options,
    key="category_filter"
)

# Region filter
region_options = ["All"] + sorted(df["Region"].unique())

selected_region = st.sidebar.selectbox(
    "🌍 Region",
    region_options,
    key="region_filter"
)

# Get the minimum and maximum dates from the dataset
min_date = df["Order Date"].min().date()
max_date = df["Order Date"].max().date()

# Start date
start_date = st.sidebar.date_input(
    "📅 Start Date",
    min_value=min_date,
    max_value=max_date,
    key="start_date_filter"
)

# End date
end_date = st.sidebar.date_input(
    "📅 End Date",
    min_value=min_date,
    max_value=max_date,
    key="end_date_filter"
)

# Validate date range
if start_date > end_date:
    st.error("⚠️ Start Date cannot be after End Date.")
    st.stop()


# Apply filters
filtered_df = df.copy()

if selected_category != "All":
    filtered_df = filtered_df[
        filtered_df["Category"] == selected_category
    ]

if selected_region != "All":
    filtered_df = filtered_df[
        filtered_df["Region"] == selected_region
    ]

filtered_df = filtered_df[
    (filtered_df["Order Date"].dt.date >= start_date) &
    (filtered_df["Order Date"].dt.date <= end_date)
]


# Display selected date range
st.caption(
    f"📅 Showing sales from {start_date.strftime('%d %b %Y')} "
    f"to {end_date.strftime('%d %b %Y')}"
)

# Calculate key performance indicators
total_sales = filtered_df["Sales"].sum()
total_orders = len(filtered_df)
total_quantity = filtered_df["Quantity"].sum()

if total_orders > 0:
    average_order_value = total_sales / total_orders
else:
    average_order_value = 0

product_sales = filtered_df.groupby("Product")["Sales"].sum()

if not product_sales.empty:
    best_product = product_sales.idxmax()
else:
    best_product = "N/A"

# Display KPI cards
with tab1:
    st.subheader("📊 Sales Overview")

    col1, col2, col3, col4, col5 = st.columns(5)

    col1.metric(
        "💰 Total Sales",
        f"₹{total_sales:,.0f}",
        help="Total revenue generated by the selected data."
    )

    col2.metric(
        "🛒 Total Orders",
        total_orders,
        help="Number of orders matching the selected filters."
    )

    col3.metric(
        "📦 Quantity Sold",
        f"{total_quantity:,}",
        help="Total number of units sold."
    )

    col4.metric(
        "💵 Avg Order Value",
        f"₹{average_order_value:,.0f}",
        help="Average revenue generated per order."
    )

    col5.metric(
        "🏆 Best Product",
        best_product,
        help="Product generating the highest revenue."
    )

    # Monthly sales analysis
    monthly_sales = filtered_df.groupby(
        filtered_df["Order Date"].dt.to_period("M").astype(str)
    )["Sales"].sum()

    st.subheader("📈 Monthly Sales Trend")

    st.line_chart(
        monthly_sales,
        x_label="Month",
        y_label="Sales Revenue (₹)",
        height=350
    )

    # Monthly sales growth
    monthly_growth = monthly_sales.pct_change() * 100

    st.subheader("📈 Monthly Sales Growth")

    st.bar_chart(
        monthly_growth,
        x_label="Month",
        y_label="Sales Growth (%)",
        height=350
    )

    # Sales by category and region
    col1, col2 = st.columns(2)

    with col1:
        category_sales = filtered_df.groupby("Category")["Sales"].sum()

        st.subheader("📊 Sales by Category")
        st.bar_chart(
            category_sales,
            y_label="Sales Revenue (₹)",
            height=350
        )

    with col2:
        region_sales = filtered_df.groupby("Region")["Sales"].sum()

        st.subheader("🌍 Sales by Region")
        st.bar_chart(
            region_sales,
            y_label="Sales Revenue (₹)",
            height=350
        )

    # Sales by product
    product_sales = filtered_df.groupby("Product")["Sales"].sum()

    st.subheader("🏆 Sales by Product")

    st.bar_chart(
        product_sales.sort_values(ascending=False),
        y_label="Sales Revenue (₹)",
        height=400
    )

    # Top product insight
    if not product_sales.empty:
        top_product = product_sales.idxmax()
        top_product_sales = product_sales.max()

        st.success(
            f"🏆 {top_product} is the top-selling product "
            f"with sales of ₹{top_product_sales:,.0f}."
        )

    # Category performance insight
    category_sales = filtered_df.groupby("Category")["Sales"].sum()

    if not category_sales.empty:
        top_category = category_sales.idxmax()
        top_category_sales = category_sales.max()

        st.info(
            f"💡 {top_category} is the top-performing category "
            f"with sales of ₹{top_category_sales:,.0f}."
        )

    # Top region insight
    if not region_sales.empty:
        top_region = region_sales.idxmax()
        top_region_sales = region_sales.max()

        st.info(
            f"🌍 {top_region} is the top-performing region "
            f"with sales of ₹{top_region_sales:,.0f}."
        )

    # ==============================
    # BUSINESS RECOMMENDATIONS
    # ==============================

    st.subheader("💡 Business Recommendations")

    if not filtered_df.empty:

        product_sales = filtered_df.groupby("Product")["Sales"].sum()
        product_quantity = filtered_df.groupby("Product")["Quantity"].sum()

        top_product = product_sales.idxmax()
        top_product_sales = product_sales.max()

        top_quantity_product = product_quantity.idxmax()
        top_quantity = product_quantity.max()

        st.info(
            f"🏆 **Focus on {top_product}** — it generates the highest "
            f"revenue with ₹{top_product_sales:,.0f} in sales."
        )

        st.info(
            f"📦 **{top_quantity_product} has the highest demand** "
            f"with {top_quantity} units sold."
        )

    else:
        st.warning(
            "No data available to generate recommendations."
        )

    # Sales performance summary
    if not filtered_df.empty:
        highest_order = filtered_df["Sales"].max()
        lowest_order = filtered_df["Sales"].min()
        average_order = filtered_df["Sales"].mean()

        st.info(
            f"📊 Sales Performance — "
            f"Highest Order: ₹{highest_order:,.0f} | "
            f"Lowest Order: ₹{lowest_order:,.0f} | "
            f"Average Order: ₹{average_order:,.0f}"
        )

    # Revenue contribution of current selection
    overall_sales = df["Sales"].sum()

    if overall_sales > 0:
        revenue_percentage = (total_sales / overall_sales) * 100
    else:
        revenue_percentage = 0

    st.progress(
        min(revenue_percentage / 100, 1.0),
        text=f"💰 Current selection represents {revenue_percentage:.2f}% of total revenue"
    )


with tab2:
    st.subheader("🔎 Sales Explorer")

    # ==============================
    # SALES EXPLORER
    # ==============================

    search_product = st.text_input(
        "Search for a product",
        placeholder="e.g. Laptop, Mouse, Desk..."
    )

    if search_product:
        search_results = filtered_df[
            filtered_df["Product"].str.contains(
                search_product,
                case=False,
                na=False
            )
        ]

        if not search_results.empty:
            st.success(
                f"Found {len(search_results)} matching orders."
            )

            search_total_sales = search_results["Sales"].sum()
            search_total_quantity = search_results["Quantity"].sum()

            col1, col2 = st.columns(2)

            col1.metric(
                "💰 Matching Sales Revenue",
                f"₹{search_total_sales:,.0f}"
            )

            col2.metric(
                "📦 Matching Units Sold",
                f"{search_total_quantity:,}"
            )

            st.dataframe(
                search_results[
                    [
                        "Order Date",
                        "Product",
                        "Category",
                        "Region",
                        "Quantity",
                        "Price",
                        "Sales"
                    ]
                ],
                    width="stretch"
                )

        else:
            st.warning(
                f"No orders found for '{search_product}'."
            )


with tab3:
    st.subheader("🧠 Ask the Data")

    # ==============================
    # ASK THE DATA
    # ==============================

    question_options = [
        "Which product generates the most revenue?",
        "Which product sells the most units?",
        "Which category generates the most revenue?",
        "Which region performs best?",
        "Which products generate high revenue with low quantity?"
    ]

    selected_question = st.selectbox(
        "What would you like to know?",
        question_options
    )

    if filtered_df.empty:
        st.warning("No sales data available for the selected filters.")

    elif selected_question == "Which product generates the most revenue?":

        product_sales = filtered_df.groupby("Product")["Sales"].sum()

        top_product = product_sales.idxmax()
        top_product_sales = product_sales.max()

        st.success(
            f"🏆 {top_product} generates the highest revenue "
            f"with ₹{top_product_sales:,.0f} in sales."
        )

        product_orders = filtered_df[
            filtered_df["Product"] == top_product
        ]

        st.write(
            f"📦 {top_product} appeared in "
            f"{len(product_orders)} orders."
        )

    elif selected_question == "Which product sells the most units?":

        product_quantity = filtered_df.groupby("Product")["Quantity"].sum()

        top_quantity_product = product_quantity.idxmax()
        top_quantity = product_quantity.max()

        st.success(
            f"📦 {top_quantity_product} sells the most units "
            f"with {top_quantity} units sold."
        )

        quantity_product_orders = filtered_df[
            filtered_df["Product"] == top_quantity_product
        ]

        st.write(
            f"🛒 {top_quantity_product} appeared in "
            f"{len(quantity_product_orders)} orders."
        )

    elif selected_question == "Which category generates the most revenue?":

        category_sales = filtered_df.groupby("Category")["Sales"].sum()

        top_category = category_sales.idxmax()
        top_category_sales = category_sales.max()

        st.success(
            f"💰 {top_category} generates the most revenue "
            f"with ₹{top_category_sales:,.0f} in sales."
        )

        category_orders = filtered_df[
            filtered_df["Category"] == top_category
        ]

        st.write(
            f"🛒 {top_category} appeared in "
            f"{len(category_orders)} orders."
        )

    elif selected_question == "Which region performs best?":

        region_sales = filtered_df.groupby("Region")["Sales"].sum()

        top_region = region_sales.idxmax()
        top_region_sales = region_sales.max()

        st.success(
            f"🌍 {top_region} is the best-performing region "
            f"with ₹{top_region_sales:,.0f} in sales."
        )

        region_orders = filtered_df[
            filtered_df["Region"] == top_region
        ]

        st.write(
            f"🛒 {top_region} had "
            f"{len(region_orders)} orders."
        )

    elif selected_question == "Which products generate high revenue with low quantity?":

        product_performance = filtered_df.groupby("Product").agg(
            Total_Sales=("Sales", "sum"),
            Total_Quantity=("Quantity", "sum")
        )

        high_revenue_low_quantity = product_performance[
            (product_performance["Total_Sales"] > product_performance["Total_Sales"].median()) &
            (product_performance["Total_Quantity"] < product_performance["Total_Quantity"].median())
        ]

        if not high_revenue_low_quantity.empty:
            st.success(
                "💡 These products generate relatively high revenue "
                "while selling relatively fewer units:"
            )

            st.dataframe(
                high_revenue_low_quantity.sort_values(
                    by="Total_Sales",
                    ascending=False
                ),
                width="stretch"
            )

        else:
            st.info(
                "No products match the high-revenue, low-quantity criteria "
                "for the selected filters."
            )


with tab4:
    st.subheader("📥 Reports & Data Quality")

    # ==============================
    # DATA QUALITY CHECK
    # ==============================

    st.subheader("🔍 Data Quality")

    missing_values = filtered_df.isnull().sum().sum()
    duplicate_rows = filtered_df.duplicated().sum()

    col1, col2 = st.columns(2)

    with col1:
        if missing_values == 0:
            st.success("✅ No missing values found.")
        else:
            st.warning(f"⚠️ {missing_values} missing values found.")

    with col2:
        if duplicate_rows == 0:
            st.success("✅ No duplicate rows found.")
        else:
            st.warning(f"⚠️ {duplicate_rows} duplicate rows found.")

    # ==============================
    # DOWNLOAD FILTERED DATA
    # ==============================

    st.subheader("📥 Export Data")

    csv_data = filtered_df.to_csv(index=False)

    st.download_button(
        label="⬇️ Download Filtered Sales Data",
        data=csv_data,
        file_name="filtered_sales_data.csv",
        mime="text/csv"
    )

    # ==============================
    # REVENUE CONTRIBUTION
    # ==============================

    st.subheader("💰 Revenue Contribution")

    if not filtered_df.empty:
        revenue_contribution = (
            filtered_df.groupby("Product")["Sales"]
            .sum()
            .sort_values(ascending=False)
        )

        revenue_percentage = (
            revenue_contribution / revenue_contribution.sum() * 100
        )

        revenue_table = pd.DataFrame({
            "Sales": revenue_contribution,
            "Revenue %": revenue_percentage
        })

        revenue_table["Revenue %"] = revenue_table["Revenue %"].round(2)

        st.dataframe(revenue_table, width="stretch")

    else:
        st.info("No sales data available for the selected filters.")

    # ==============================
    # DOWNLOAD PRODUCT PERFORMANCE REPORT
    # ==============================

    st.subheader("📥 Download Product Performance Report")

    if not filtered_df.empty:
        product_report = filtered_df.groupby("Product").agg(
            Total_Quantity=("Quantity", "sum"),
            Total_Sales=("Sales", "sum")
        )

        product_report["Revenue_Percentage"] = (
            product_report["Total_Sales"]
            / product_report["Total_Sales"].sum()
            * 100
        ).round(2)

        product_report = product_report.sort_values(
            by="Total_Sales",
            ascending=False
        )

        report_csv = product_report.to_csv(index=True)

        st.download_button(
            label="📊 Download Product Report",
            data=report_csv,
            file_name="product_performance_report.csv",
            mime="text/csv"
        )

    else:
        st.info("No data available to generate a report.")

    # ==============================
    # QUANTITY VS REVENUE
    # ==============================

    st.subheader("📦 Quantity vs Revenue")

    if not filtered_df.empty:
        product_performance = filtered_df.groupby("Product").agg(
            Total_Quantity=("Quantity", "sum"),
            Total_Sales=("Sales", "sum")
        )

        st.dataframe(
            product_performance.sort_values(
                by="Total_Sales",
                ascending=False
            ),
            width="stretch"
        )

        st.subheader("📦 Quantity vs Revenue Relationship")

        st.scatter_chart(
            product_performance,
            x="Total_Quantity",
            y="Total_Sales",
            x_label="Total Quantity Sold",
            y_label="Total Sales Revenue (₹)",
            height=400
        )

    else:
        st.info("No data available for Quantity vs Revenue analysis.")

    # ==============================
    # FILTERED SALES DATA
    # ==============================

    st.subheader("📋 Filtered Sales Data")

    st.caption(
        f"Showing {len(filtered_df)} orders matching the selected filters."
    )

    st.dataframe(filtered_df, width="stretch")

    # ==============================
    # DATASET INFORMATION
    # ==============================

    st.subheader("📋 Dataset Information")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric(
            "📦 Filtered Records",
            len(filtered_df)
        )

    
    with col2:
        st.metric(
            "📅 Selected Start Date",
            start_date.strftime("%d %b %Y")
        )

    with col3:
        st.metric(
            "📅 Selected End Date",
            end_date.strftime("%d %b %Y")
        )
